### ISSUE TITLE
Problems about trying examples in documentation

### ISSUE THREAD

**Issue by OnlyEpisode** [samuelmurail/docking_py#9]
Hello! When I try to extract affinity and RMSD to crystal structure in examples "rmsd_list = test_dock.compute_dock_rmsd(test_dock.lig_pdbqt)", it appears that "File name doesn't finish with .pdb read it as .pdb anyway".
And then I try "rmsd_list = test_dock.compute_dock_rmsd(test_dock.lig_pdb)", value errors appear:
"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.conda/envs/docking/lib/python3.6/site-packages/docking_py-0.2.3-py3.6.egg/docking_py/docking.py", line 1382, in compute_dock_rmsd
    rmsd = dock_coor.compute_rmsd_to(cryst_coor, selec_dict=selec_dict)
  File "/home/xxx/.conda/envs/docking/lib/python3.6/site-packages/pdb_manip_py/pdb_manip.py", line 3932, in compute_rmsd_to
    rmsd = atom_coor.compute_rmsd_to(atom_sel_2, selec_dict=selec_dict)
  File "/home/xxx/.conda/envs/docking/lib/python3.6/site-packages/pdb_manip_py/pdb_manip.py", line 2545, in compute_rmsd_to
    diff = coor_array_1 - coor_array_2
ValueError: operands could not be broadcast together with shapes (50,3) (45,3) 
"
And the computed rmsd_list is also very different from the one shown in examples. 

How to fix it? Thank you!

**Comment by samuelmurail** [comment]
Hi,

The message "File name doesn't finish with .pdb read it as .pdb anyway"
is just a warning, as you are using a pdbqt file. It is fine and expected

Concerning the RMSD calculation :
```
rmsd_list = test_dock.compute_dock_rmsd(test_dock.lig_pdb)
```

You should use the ``test_dock.lig_pdbqt`` as reference structure instead. Otherwise the atom number is different, this is an issue for RMSD calculation.
The difference in rmsd, is also expected, as you cannot run exactly the same run on different machines.

Anyway, I have updated the Usage page, and add exemples to look with `nglview` at the dock structures:
https://docking-py.readthedocs.io/en/latest/notebook/Usage.html

To enbale the 3D viz, you'll need to install nglview and mdanalysis:
```
conda install -c conda-forge nglview
conda install -c conda-forge MDAnalysis
```

Cheers,
Samuel
